version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: nuget restore Araye.Code.Cqrs.WebApi.sln
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: AsYP0IzROChbHum3fvSyS32pEFBHyjtDTEh61XbP9VidCX7XpFGDhlkhPirxDft2